### ISSUE TITLE
Purple description paragraph doesn't register in Demo

### ISSUE THREAD

**Issue by NOT-HAL9000** [words/color-description#11]
Purple doesn't show up between hsl(270,100%,50%) and hsl(290,100%,50%)

**Comment by meodai** [comment]
@NOT-HAL9000 sorry it took me a while but it was fixed in https://github.com/words/color-description/commit/a353ebecd034507a6a9c85de1c7b11fe7dcd3fc4#diff-a8deb9fd18a643eacbcd423a0c8959cb36e08cbb5e207134748e72b1d6170452R1093
