### ISSUE TITLE
color picker keyboard accessible

### ISSUE THREAD

**Issue by nico-martin** [words/color-description#4]
I think it would be great if the color picker would be keyboard accessible.
The little circles could be a button (focusable) and you could move them with the keys :)

**Comment by meodai** [comment]
@nico-martin oh I set it to aria-hidden and  the browser's native color picker is .visually-hidden

**Comment by meodai** [comment]
@nico-martin can you have  a look at the new demo? try tabbing

**Comment by nico-martin** [comment]
Oh, that's nice 👍

**Comment by nico-martin** [comment]
Would it also make sense to add the a url-hash with the current color?
Then it would also be possible to open https://words.github.io/color-description/#ff0000 and have directly the red color active.

**Comment by meodai** [comment]
@nico-martin the HTML is just a demo not the tool it self. The bundle "only" ships the class that can identify the color. Feel free to make a project out of it! Would love to see that. (I am already using it here: https://parrot.color.pizza/color/980fff/%E2%9D%A4 in the top section)
